@baseAPIUrl=http://localhost:8000/api

###
GET {{baseAPIUrl}}/products/ HTTP/1.1

###
POST {{baseAPIUrl}}/products/ HTTP/1.1
Content-Type: application/json

{
  "name": "abc",
  "price": "10000",
  "pictureUrl": "uabobobwo",
  "type": "ubobuwvyvobo2",
  "brand": "ubobuwvyvobo2",
  "quantityInStock": "10"
}

###
GET {{baseAPIUrl}}/products/10 HTTP/1.1

###
PUT {{baseAPIUrl}}/products/110 HTTP/1.1
Content-Type: application/json

{
  "name": "hahahahahahhahahahahha"
}