# Generated by Django 5.2.1 on 2025-06-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.BigIntegerField()),
                ('picture_url', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('quantity_in_stock', models.IntegerField()),
            ],
        ),
    ]
